model_name: "text_diffusion"
model_output_path: 
mixed_precision: "fp16"
seed: 17
seq_length: 1000
n_channels: 12
metadata_df_paths:
  train_metadata_path: 
  eval_metadata_path: 
  test_metadata_path:
batch_size: 32
gen_eval_batch_size: 32
num_epochs: 5
loss_fn: mse
optimizer: adamw
optimizer_kwargs:
  lr: 0.0001
lr_warmup_steps: 1000
noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_schedule: "squaredcos_cap_v2"
cuda_idx: 0
accumulate_grads_every_x_steps: 1
gen_eval_every_x_batches: 2000
eval_metrics_every_x_batches: 2000
save_model_epochs: 2
push_to_hub: false
hub_model_id: "None"